[package]
name = "logger"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = "0.9.9"
core_affinity = "0.8"
crossbeam = "0.8.4"
crossbeam-utils = "0.8.21"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
questdb-rs = "6.1.0"
